version: '3.5'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=login12345
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef